name: TestA

on: [push]

jobs:
  start-workflow:
    if: "!contains(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Other Workflow
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger-testb"}')
          cat response.txt
          echo "Response code: $response"
