name: Mac UserServer Build

on:
  repository_dispatch:
    types: [trigger-userserver-build]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Read Config File
        id: read_config
        run: |
          while IFS=: read -r key value; do
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            echo "$key=$value" >> $GITHUB_ENV
          done < config.txt
        shell: bash

      - name: Setup Node.js environment for packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      
      - name: Install pkg
        run: npm install -g pkg

      - name: Get number of releases
        id: get_releases
        run: |
          releases=$(curl -s -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100" | jq -r '. | length')
          releases=$(echo $releases | xargs)
          echo "releases=$releases" >> $GITHUB_ENV

      - name: Download version artifact from previous workflow
        uses: actions/download-artifact@v2
        with:
          name: version

      - name: Read version
        id: read_version
        run: |
          version=$(cat version.txt)
          echo "version=$version" >> $GITHUB_ENV

      - name: Build executable
        run: pkg main.js --targets latest-macos-x64 --output userServer_mac

      - name: Upload userServer_mac as artifact
        uses: actions/upload-artifact@v4
        with:
          name: userServer_mac_${{ env.version }}
          path: userServer_mac

      - name: Check if release exists
        id: check_release
        run: |
          release_url=$(curl -s -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.version }}" | jq -r '.url')
          if [ "$release_url" == "null" ]; then
            echo "release_exists=false" >> $GITHUB_ENV
          else
            echo "release_exists=true" >> $GITHUB_ENV
            echo "release_url=$release_url" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Create or Get Release
        id: create_or_get_release
        if: env.is_release == 'true'
        run: |
          if [ "${{ env.release_exists }}" == "true" ]; then
            echo "Using existing release."
            echo "upload_url=$(curl -s -H 'Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}' ${{ env.release_url }} | jq -r '.upload_url' | sed -e 's/{?name,label}//')" >> $GITHUB_ENV
          else
            echo "Creating new release."
            response=$(curl -s -X POST -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"tag_name\": \"${{ env.version }}\", \"name\": \"Release ${{ env.version }}\", \"body\": \"Automated release\", \"draft\": false, \"prerelease\": ${{ env.is_prerelease == 'true' }}}" \
              "https://api.github.com/repos/${{ github.repository }}/releases")
            echo "upload_url=$(echo $response | jq -r '.upload_url' | sed -e 's/{?name,label}//')" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Upload Release Asset
        if: env.is_release == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SKEDAI_ACTION_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: userServer_mac
          asset_name: userServer_mac_${{ env.version }}
          asset_content_type: application/octet-stream
