name: Mac UserServer Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment for packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      
      - name: Install pkg
        run: npm install -g pkg

      - name: Get number of releases
        id: get_releases
        run: |
          releases=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases?per_page=1" | jq -r '.[].id' | wc -l)
          releases=$(echo $releases | xargs)
          echo "releases=$releases" >> $GITHUB_ENV

      - name: Get number of commits
        id: get_commits
        run: |
          commits=$(git rev-list --count HEAD)
          commits=$(echo $commits | xargs)
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Set version number
        id: set_version
        run: |
          version="0.${{ env.releases }}.${{ env.commits }}"
          version=$(echo $version | xargs)
          echo "version=$version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Build executable
        run: pkg main.js --targets latest-macos-x64 --output userServer_mac

      - name: Upload userServer_mac as artifact
        uses: actions/upload-artifact@v4
        with:
          name: userServer_mac_${{ env.version }}
          path: userServer_mac
