name: Mac UserServer Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Read Config File
        id: read_config
        run: |
          while IFS=: read -r key value; do
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            echo "$key=$value" >> $GITHUB_ENV
          done < config.txt
        shell: bash

      - name: Setup Node.js environment for packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      
      - name: Install pkg
        run: npm install -g pkg

      - name: Get number of releases
        id: get_releases
        run: |
          releases=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases?per_page=1" | jq -r '.[].id' | wc -l)
          releases=$(echo $releases | xargs)
          echo "releases=$releases" >> $GITHUB_ENV

      - name: Get number of commits
        id: get_commits
        run: |
          commits=$(git rev-list --count HEAD)
          commits=$(echo $commits | xargs)
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Set version number
        id: set_version
        run: |
          version="0.${{ env.releases }}.${{ env.commits }}"
          version=$(echo $version | xargs)
          echo "version=$version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Build executable
        run: pkg main.js --targets latest-macos-x64 --output userServer_mac

      - name: Upload userServer_mac as artifact
        uses: actions/upload-artifact@v4
        with:
          name: userServer_mac_${{ env.version }}
          path: userServer_mac
      
      - name: Calculate Release Version
        id: calculate_version
        if: env.is_release == 'true'
        run: |
          release_version="0.$((${{ env.releases }} + 1)).${{ env.commits }}"
          echo "RELEASE_VERSION=$release_version"
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
        shell: bash

      - name: Create Release
        id: create_release
        if: env.is_release == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SKEDAI_ACTION_TOKEN }}
        with:
          tag_name: "${{ env.RELEASE_VERSION }}"
          release_name: "Test Automated Release"
          body: |
            This is an automated test release
          draft: false
          prerelease: ${{ env.is_prerelease == 'true' }}
      
      - name: Upload Release Asset
        if: env.is_release == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SKED_ACTION_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: userServer_mac
          asset_name: userServerMac
          asset_content_type: application/octet-stream

