name: Mac UserServer Build

on:
  workflow_run:
    workflows: ["Calculate Version and Trigger Build"]
    types:
      - completed

jobs:
  build:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            })
            const matchArtifact = artifacts.data.artifacts.find(artifact => artifact.name === "version")
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip'
            })
            fs.writeFileSync('version.zip', Buffer.from(download.data))
      - run: unzip version.zip

      - name: Read version
        run: |
          version=$(cat version.txt)
          echo "version=$version" >> $GITHUB_ENV
      
      - name: Read Config File
        id: read_config
        run: |
          while IFS=: read -r key value; do
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            echo "$key=$value" >> $GITHUB_ENV
          done < config.txt
        shell: bash

      - name: Setup Node.js environment for packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      
      - name: Install pkg
        run: npm install -g pkg

      - name: Get number of releases
        id: get_releases
        run: |
          releases=$(curl -s -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100" | jq -r '. | length')
          releases=$(echo $releases | xargs)
          echo "releases=$releases" >> $GITHUB_ENV

      - name: Build executable
        run: pkg main.js --targets latest-macos-x64 --output userServer_mac

      - name: Upload userServer_mac as artifact
        uses: actions/upload-artifact@v4
        with:
          name: userServer_mac_${{ env.version }}
          path: userServer_mac

      - name: Check if release exists
        id: check_release
        run: |
          release_url=$(curl -s -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.version }}" | jq -r '.url')
          if [ "$release_url" == "null" ]; then
            echo "release_exists=false" >> $GITHUB_ENV
          else
            echo "release_exists=true" >> $GITHUB_ENV
            echo "release_url=$release_url" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Create or Get Release
        id: create_or_get_release
        if: env.is_release == 'true'
        run: |
          if [ "${{ env.release_exists }}" == "true" ]; then
            echo "Using existing release."
            upload_url=$(curl -s -H 'Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}' ${{ env.release_url }} | jq -r '.upload_url')
            echo "upload_url=$upload_url" >> $GITHUB_ENV
          else
            echo "Creating new release."
            response=$(curl -s -X POST -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"tag_name\": \"${{ env.version }}\", \"name\": \"Release ${{ env.version }}\", \"body\": \"Automated release\", \"draft\": false, \"prerelease\": ${{ env.is_prerelease == 'true' }}}" \
              "https://api.github.com/repos/${{ github.repository }}/releases")
            upload_url=$(echo $response | jq -r '.upload_url')
            echo "upload_url=$upload_url" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Debugging Information
        run: |
          echo "Upload URL: ${{ env.upload_url }}"
          echo "Asset Path: userServer_mac"
          echo "Asset Name: userServer_mac_${{ env.version }}"

      - name: Upload Release Asset
        if: env.is_release == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SKEDAI_ACTION_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: userServer_mac
          asset_name: "userServer_mac_${{ env.version }}"
          asset_content_type: application/octet-stream
